spring.application.name=lms

spring.datasource.url=jdbc:postgresql://localhost:5432/db_iums_lms
spring.datasource.username=postgres
spring.datasource.password=ig100
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080